name: test flaml from automlbenchmark

on:
  push:
    branches: ['benchmark']
  pull_request:
    branches: ['benchmark']


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run job 1
      run: bash test.sh
      working-directory: cli
    - name: setup az
      run: bash setup.sh
      working-directory: cli
      continue-on-error: true
    - name: run flaml from automlbenchmark
      run: bash setup_benchmark.sh
      working-directory: cli